services:
  - postgresql
language: node_js
node_js:
  - "12.16.3"
install:
  - cp .env.example .env
  - yarn install
env:
  - DB_USER="postgres" DB_PASSWORD="" DB_HOST="localhost" DB_NAME="test_postgres_db"
before_script:
  - psql -c 'create database test_postgres_db;' -U postgres
script:
  - yarn typeorm migration:run
  - yarn seed:run
  - yarn ci:test
  - yarn lint:eslint
  - yarn ejslint
notifications:
  email: false