language: node_js
node_js:
  - "8.9.4"
install:
  - yarn install
  - cp .env.example .env
  - yarn typeorm migration:run
  - yarn seed:run
env:
  - DB_TYPE="sqlite" DB_DATABASE="./testDB.db" DB_LOGGING=false
script:
  - yarn test
  - yarn lint:eslint
notifications:
  email: false