services:
  - postgresql
language: node_js
node_js:
  - "12.16.3"
install:
  - cp .env.example .env
  - yarn install
  - yarn typeorm migration:run
  - yarn seed:run
script:
  - yarn ci:test
  - yarn lint:eslint
  - yarn ejslint
notifications:
  email: false