services:
  - postgresql
language: node_js
node_js:
  - "12.16.3"
env:
  - NODE_ENV="travis" DB_USER="postgres" DB_PASSWORD="" DB_HOST="localhost" DB_NAME="test_postgres_db"
before_install:
  - psql -c 'create database test_postgres_db;' -U postgres
install:
  - cp .env.example .env
  - yarn install
  - yarn build
  - yarn db migration:run
  - yarn db:seeding seed
script:
  - yarn test
  - yarn prod:test
  - yarn eslint
  - yarn ejslint
notifications:
  email: false